### ISSUE TITLE
Message d'erreur sous excel

### ISSUE THREAD

**Issue by Keldane** [BdR76/barcode128.bas#2]
Bonjour,

Je reçois un message d'erreur lorsque je souhaite l'utiliser sous Excel : 
"erreur de compilation attendu fin d'instruction"

Et je ne peux pas importer le fichier .bas le message reçu est "Instruction trop complexe".
Je doit mal faire quelque chose...

Merci
<img width="1430" alt="Capture d’écran 2021-09-17 à 11 47 02" src="https://user-images.githubusercontent.com/86516724/133762940-1e32074e-5869-4ef0-a6ed-b8ebd446b032.png">

**Comment by BdR76** [comment]
Mon français n'est pas très bon mais je vais essayer de répondre.

Je ne sais pas comment vous avez importé le code dans Excel, mais il me semble que tout le texte, le code et les commentaires été traduits en français. Y compris le code source, les fonctions et les mots-clés, qui, à mon avis, ne devraient pas du tout être traduits. Avez-vous peut-être un plug-in de navigateur qui traduit automatiquement tous les textes en français?

Je pense qu'il est préférable de simplement supprimer tout le code que vous avez maintenant, et de l'écraser avec [le code de cette page](https://github.com/BdR76/barcode128.bas/blob/master/barcode128.bas) (juste le code, et pas traduit en Français). Allez donc sur la page de code source d'origine, sélectionnez tout et copiez (CTRL+A et CTRL+C) et collez-le dans votre fenêtre de code source Module1. Peut-être est-il plus simple [d'ouvrir cette page](https://github.com/BdR76/barcode128.bas/blob/master/barcode128.bas)?

**Comment by Keldane** [comment]
Indeed, my google translate was active. I'm terrible...

**Comment by Keldane** [comment]
It works fine ! Thanks !

**Comment by BdR76** [comment]
Ok great, and no problem, as they say: "the only one who makes no mistakes, is someone who never does anything".
I assume this can be closed then.
cheers,
Bas
